export type Role = 'PILGRIM'|'AGENT'|'CLINICIAN'|'NURSE'|'ALLIED_HEALTH'|'PHARMACIST'|'ADMIN'|'MEDICAL_DIRECTOR';
export type AppointmentPurpose = 'SCREENING'|'VACCINATION'|'SCREENING_AND_VACCINATION'|'REVIEW';
export type AuditAction = 'CREATE'|'READ'|'UPDATE'|'DELETE'|'LOGIN'|'LOGIN_FAILED'|'OTP_SENT'|'OTP_VERIFIED'|'OVERRIDE'|'EXPORT'|'BREAK_GLASS';
export type JsonValue = any;
