import type { FastifyInstance } from 'fastify';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { requireRoles } from '../lib/authz.js';
import { audit } from '../lib/audit.js';

const requisition=z.object({clinicName:z.string().min(2),period:z.enum(['DAILY','WEEKLY']),justification:z.string().min(3),items:z.array(z.object({inventoryItemId:z.string().uuid(),quantity:z.number().int().positive()})).min(1)});
const supply=z.object({items:z.array(z.object({requisitionItemId:z.string().uuid(),quantity:z.number().int().nonnegative()})).min(1)});
const receipt=z.object({code:z.string().trim().min(2),genericName:z.string().trim().min(2),formulation:z.string().trim().min(2),strength:z.string().trim().min(1),unit:z.string().trim().min(1),quantity:z.number().int().positive(),reorderLevel:z.number().int().nonnegative(),location:z.string().trim().min(2).default('CENTRAL_STORE')});
const dispense=z.object({idempotencyKey:z.string().uuid(),prescriptionReference:z.string().trim().min(3),pilgrimId:z.string().uuid(),inventoryItemId:z.string().uuid(),quantity:z.number().int().positive()});

export async function pharmacyRoutes(app:FastifyInstance){
  app.get('/inventory',{preHandler:requireRoles('PHARMACIST','ADMIN')},async()=>prisma.inventoryItem.findMany({where:{active:true},orderBy:[{genericName:'asc'},{strength:'asc'}]}));
  app.get('/availability',{preHandler:requireRoles('PHARMACIST','ADMIN')},async req=>{const q=z.object({search:z.string().trim().min(1)}).parse(req.query);return prisma.inventoryItem.findMany({where:{active:true,OR:[{genericName:{contains:q.search,mode:'insensitive'}},{formulation:{contains:q.search,mode:'insensitive'}},{strength:{contains:q.search,mode:'insensitive'}}]},select:{id:true,code:true,genericName:true,formulation:true,strength:true,unit:true,quantity:true,reorderLevel:true,location:true},take:25})});
  app.post('/inventory/receipts',{preHandler:requireRoles('PHARMACIST','ADMIN')},async(req,reply)=>{const b=receipt.parse(req.body),row=await prisma.inventoryItem.upsert({where:{code:b.code.toUpperCase()},create:{...b,code:b.code.toUpperCase()},update:{quantity:{increment:b.quantity},reorderLevel:b.reorderLevel,active:true}});await audit(req,{action:'CREATE',subjectType:'StockReceipt',subjectId:row.id,metadata:{quantity:b.quantity,location:b.location}});return reply.code(201).send(row)});
  app.post('/dispenses',{preHandler:requireRoles('CLINICIAN','PHARMACIST','ADMIN')},async(req,reply)=>{const b=dispense.parse(req.body),row=await prisma.$transaction(async tx=>{const prior=await tx.medicationDispense.findUnique({where:{idempotencyKey:b.idempotencyKey}});if(prior)return prior;const stock=await tx.inventoryItem.findUniqueOrThrow({where:{id:b.inventoryItemId}});if(stock.quantity<b.quantity)throw Object.assign(new Error('Medicine cannot currently be supplied'),{statusCode:409,code:'INSUFFICIENT_STOCK'});await tx.inventoryItem.update({where:{id:stock.id},data:{quantity:{decrement:b.quantity}}});return tx.medicationDispense.create({data:{...b,dispensedByUserId:req.user.sub}})},{isolationLevel:'Serializable'});await audit(req,{action:'CREATE',subjectType:'MedicationDispense',subjectId:row.id,patientId:b.pilgrimId,metadata:{prescriptionReference:b.prescriptionReference,quantity:b.quantity,role:req.user.role}});return reply.code(201).send(row)});
  app.get('/dispenses',{preHandler:requireRoles('CLINICIAN','PHARMACIST','ADMIN')},async req=>{const q=z.object({pilgrimId:z.string().uuid().optional()}).parse(req.query);return prisma.medicationDispense.findMany({where:{pilgrimId:q.pilgrimId},include:{inventoryItem:{select:{code:true,genericName:true,formulation:true,strength:true,unit:true}}},orderBy:{dispensedAt:'desc'},take:250})});
  app.post('/requisitions',{preHandler:requireRoles('NURSE')},async(req,reply)=>{const b=requisition.parse(req.body),unique=new Map(b.items.map(x=>[x.inventoryItemId,x]));if(unique.size!==b.items.length)return reply.code(409).send({error:{code:'DUPLICATE_REQUISITION_ITEM',message:'Each stock item may appear only once per requisition'}});const row=await prisma.requisition.create({data:{reference:`REQ-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${randomUUID().slice(0,6).toUpperCase()}`,clinicName:b.clinicName,period:b.period,justification:b.justification,requestedByUserId:req.user.sub,items:{create:b.items.map(x=>({inventoryItemId:x.inventoryItemId,requestedQuantity:x.quantity}))}},include:{items:{include:{inventoryItem:true}}}});await audit(req,{action:'CREATE',subjectType:'PharmacyRequisition',subjectId:row.id,metadata:{clinicName:b.clinicName,period:b.period}});return reply.code(201).send(row)});
  app.get('/requisitions',{preHandler:requireRoles('NURSE','PHARMACIST','ADMIN')},async req=>{const rows=await prisma.requisition.findMany({include:{items:{include:{inventoryItem:true}}},orderBy:{createdAt:'desc'},take:250});if(req.user.role==='NURSE')return rows.map(r=>({...r,items:r.items.map(x=>({id:x.id,inventoryItemId:x.inventoryItemId,itemName:x.inventoryItem.genericName,status:x.suppliedQuantity>=x.requestedQuantity?'SUPPLIED':'PENDING'}))}));return rows});
  app.post('/requisitions/:id/supply',{preHandler:requireRoles('PHARMACIST','ADMIN')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),b=supply.parse(req.body);const updated=await prisma.$transaction(async tx=>{const r=await tx.requisition.findUniqueOrThrow({where:{id},include:{items:true}});if(['SUPPLIED','CANCELLED'].includes(r.status))throw Object.assign(new Error('This requisition cannot be supplied again'),{statusCode:409,code:'REQUISITION_CLOSED'});for(const issue of b.items){const line=r.items.find(x=>x.id===issue.requisitionItemId);if(!line)throw Object.assign(new Error('Supply item does not belong to this requisition'),{statusCode:422,code:'REQUISITION_ITEM_MISMATCH'});if(issue.quantity>line.requestedQuantity-line.suppliedQuantity)throw Object.assign(new Error('Supplied quantity exceeds outstanding quantity'),{statusCode:422,code:'SUPPLY_EXCEEDS_REQUEST'});const stock=await tx.inventoryItem.findUniqueOrThrow({where:{id:line.inventoryItemId}});if(issue.quantity>stock.quantity)throw Object.assign(new Error(`${stock.genericName} has insufficient stock`),{statusCode:409,code:'INSUFFICIENT_STOCK'});await tx.inventoryItem.update({where:{id:stock.id},data:{quantity:{decrement:issue.quantity}}});await tx.requisitionItem.update({where:{id:line.id},data:{suppliedQuantity:{increment:issue.quantity}}})}const lines=await tx.requisitionItem.findMany({where:{requisitionId:id}}),complete=lines.every(x=>x.suppliedQuantity>=x.requestedQuantity);return tx.requisition.update({where:{id},data:{status:complete?'SUPPLIED':'PART_SUPPLIED',suppliedByUserId:req.user.sub,suppliedAt:new Date()},include:{items:{include:{inventoryItem:true}}}})} ,{isolationLevel:'Serializable'});await audit(req,{action:'UPDATE',subjectType:'PharmacyRequisitionSupply',subjectId:id,metadata:{status:updated.status}});return reply.send(updated)});
}
