import { prisma } from '../lib/prisma.js';
import type { Prisma } from '@prisma/client';
type Recipient={phone?:string|null;email?:string|null;recipientType:string};
type AppointmentEvent='CONFIRMED'|'AMENDED'|'CANCELLED';
async function queueDual(recipient:Recipient,template:string,payload:Prisma.InputJsonValue,appointmentId?:string){const rows=[...(recipient.phone?[{destination:recipient.phone,channel:'SMS' as const}]:[]),...(recipient.email?[{destination:recipient.email.toLowerCase(),channel:'EMAIL' as const}]:[])];if(rows.length)await prisma.notification.createMany({data:rows.map(row=>({appointmentId,recipientType:recipient.recipientType,destination:row.destination,channel:row.channel,template,payload}))})}
export async function queueRegistrationNotifications(input:Recipient&{pilgrimName:string;passportNumber:string}){await queueDual(input,'PORTAL_REGISTRATION',{pilgrimName:input.pilgrimName,passportNumber:input.passportNumber,message:'Your HajjMed Ghana pilgrim portal registration is complete.'})}
export async function queueAppointmentNotifications(input:Recipient&{event:AppointmentEvent;appointmentId:string;reference:string;pilgrimName:string;date:Date;venue:string;purpose:string}){await queueDual(input,`APPOINTMENT_${input.event}`,{reference:input.reference,pilgrimName:input.pilgrimName,date:input.date.toISOString(),venue:input.venue,purpose:input.purpose,preparation:'Blood and urine samples may be taken. Imaging investigations may also be conducted.'},input.appointmentId)}
export async function queueScreeningOutcomeNotifications(input:Recipient&{pilgrimName:string;outcome:'GREEN'|'AMBER'|'RED';recommendations?:string|null}){await queueDual(input,input.outcome==='GREEN'?'SCREENING_GREEN':'SCREENING_REVIEW_REQUIRED',{pilgrimName:input.pilgrimName,outcome:input.outcome,recommendations:input.recommendations,message:input.outcome==='GREEN'?'You have met the medical screening requirements for Hajj.':'Further clinical review is required. Follow the recommendations and await or book the authorised review appointment.'})}

async function contactContext(pilgrimId:string){return prisma.pilgrim.findUniqueOrThrow({where:{id:pilgrimId},include:{user:{select:{phoneNormalized:true,email:true}},organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'},select:{phoneNormalized:true,email:true}}}}}})}

export async function queuePilgrimPortalUpdateNotifications(input:{pilgrimId:string;updateType:string}){
  const pilgrim=await contactContext(input.pilgrimId),pilgrimName=`${pilgrim.givenNames} ${pilgrim.surname}`;
  await queueDual({phone:pilgrim.user?.phoneNormalized,email:pilgrim.user?.email,recipientType:'PILGRIM'},'PILGRIM_PORTAL_UPDATED',{pilgrimName,updateType:input.updateType,message:'There is an update on your HajjMed Ghana portal. Sign in securely to review it. No clinical details are included in this message.'});
}

export async function queueCertificateReadyNotifications(input:{pilgrimId:string;certificateType:string;certificateReference:string}){
  const pilgrim=await contactContext(input.pilgrimId),pilgrimName=`${pilgrim.givenNames} ${pilgrim.surname}`,payload={pilgrimName,certificateType:input.certificateType,certificateReference:input.certificateReference,message:`The ${input.certificateType} has been authenticated and is ready for printing. Sign in securely to HajjMed Ghana.`};
  await queueDual({phone:pilgrim.user?.phoneNormalized,email:pilgrim.user?.email,recipientType:'PILGRIM'},'CERTIFICATE_READY',payload);
  for(const agent of pilgrim.organization?.users??[])await queueDual({phone:agent.phoneNormalized,email:agent.email,recipientType:'AGENT'},'CERTIFICATE_READY',payload);
}

export async function queueDueAppointmentReminders(now=new Date()){
  const intervals=[48,24,12,6,1],windowMs=10*60_000,end=new Date(now.getTime()+48*60*60_000),appointments=await prisma.appointment.findMany({where:{status:{in:['CONFIRMED','CHECKED_IN']},startsAt:{gt:now,lte:end}},include:{facility:true,pilgrim:{include:{user:true,organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'}}}}}}}});let queued=0;
  for(const a of appointments)for(const hours of intervals){const due=a.startsAt.getTime()-hours*60*60_000;if(now.getTime()<due||now.getTime()-due>=windowMs)continue;const template=`APPOINTMENT_REMINDER_${hours}H`,payload={reference:a.reference,pilgrimName:`${a.pilgrim.givenNames} ${a.pilgrim.surname}`,date:a.startsAt.toISOString(),venue:a.facility.name,purpose:a.purpose,hoursBefore:hours,message:`Your HajjMed appointment is in ${hours} hour${hours===1?'':'s'}. Bring your passport and arrive before the session.`};for(const recipient of [{phone:a.pilgrim.user?.phoneNormalized,email:a.pilgrim.user?.email,recipientType:'PILGRIM' as const},...(a.pilgrim.organization?.users??[]).map(u=>({phone:u.phoneNormalized,email:u.email,recipientType:'AGENT' as const}))]){const exists=await prisma.notification.findFirst({where:{appointmentId:a.id,recipientType:recipient.recipientType,template},select:{id:true}});if(!exists){await queueDual(recipient,template,payload,a.id);queued++}}}
  return {appointmentsChecked:appointments.length,recipientReminderGroupsQueued:queued,intervalHours:intervals};
}

export async function queueCommunicationActionNotifications(input:{threadId:string;actorUserId:string;event:'OPENED'|'MESSAGE'|'ASSIGNED'|'RESOLVED'}){
  const thread=await prisma.communicationThread.findUniqueOrThrow({where:{id:input.threadId},include:{pilgrim:{include:{user:true,organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'}}}}}}}}),actor=await prisma.user.findUniqueOrThrow({where:{id:input.actorUserId},select:{role:true,displayName:true}}),assignedTo=thread.assignedToUserId?await prisma.user.findUnique({where:{id:thread.assignedToUserId}}):null,directRecipient=thread.directRecipientUserId?await prisma.user.findUnique({where:{id:thread.directRecipientUserId}}):null,opener=await prisma.user.findUnique({where:{id:thread.openedByUserId}}),recipients:{id:string;phoneNormalized:string|null;email:string|null;professionalEmail:string|null;role:string}[]=[];
  if(directRecipient){const other=input.actorUserId===directRecipient.id?opener:directRecipient;if(other&&other.id!==input.actorUserId)recipients.push(other)}else if(actor.role==='PILGRIM'&&thread.recipientGroup==='AGENT'){for(const agent of thread.pilgrim.organization?.users??[])if(agent.id!==input.actorUserId)recipients.push(agent)}else if(['PILGRIM','AGENT'].includes(actor.role)){if(assignedTo&&assignedTo.id!==input.actorUserId)recipients.push(assignedTo);else recipients.push(...await prisma.user.findMany({where:{status:'ACTIVE',role:{in:['CLINICIAN','NURSE']},id:{not:input.actorUserId}},select:{id:true,phoneNormalized:true,email:true,professionalEmail:true,role:true},take:20}))}else{if(thread.pilgrim.user&&thread.pilgrim.user.id!==input.actorUserId)recipients.push(thread.pilgrim.user);for(const agent of thread.pilgrim.organization?.users??[])if(agent.id!==input.actorUserId)recipients.push(agent);if(assignedTo&&assignedTo.id!==input.actorUserId)recipients.push(assignedTo)}
  const unique=[...new Map(recipients.map(x=>[x.id,x])).values()],payload={threadId:thread.id,reference:thread.reference,subject:thread.subject,event:input.event,actor:actor.displayName,message:'A secure HajjMed conversation requires your attention. Sign in to view and respond; clinical details are not included in this notification.'};for(const recipient of unique)await queueDual({phone:recipient.phoneNormalized,email:recipient.professionalEmail||recipient.email,recipientType:recipient.role},`COMMUNICATION_${input.event}`,payload);return {recipientsQueued:unique.length};
}
