if(!patients.some(p=>p.passport==='G2786087'))patients.push({id:'GH27-005010',name:'Amina Mohammed',initials:'AM',age:44,sex:'Female',agent:'Direct Hajj pilgrim',region:'Northern',phone:'024 700 6087',status:'Not screened',risk:'Unassessed',finding:'',condition:'Not yet assessed',blood:'',vax:'Due',screen:'Pending',last:'Registered · no appointment',passport:'G2786087',surname:'Mohammed',given:'Amina',dob:'1982-05-14',nationality:'Ghanaian',expiry:'2031-11-20',photo:null,emergencyContact:{name:'Pending completion',phone:'',relationship:''}});
function confirmedAppointmentFor(pilgrim,service){return state.confirmedAppointments.some(a=>a.pilgrimId===pilgrim.id&&a.status==='Confirmed'&&(a.service===service||a.service==='both'))}
function showAppointmentRequired(pilgrim,service){let label=service==='screening'?'medical screening':'vaccination',modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card appointment-gate"><div class="modal-head"><div><span class="eyebrow" style="color:var(--red)">Access blocked</span><h2>Confirmed appointment required</h2><p class="sub">The ${label} portal cannot be opened for this pilgrim without a matching confirmed appointment.</p></div><button class="iconbtn closeGate">×</button></div><div class="passport-rule">${icon('alert')}<div><strong>${pilgrim.name}</strong><span>Passport ${pilgrim.passport} · No confirmed ${label} appointment is on record.</span></div></div><div class="modal-actions"><span>Book and confirm an available regional slot first.</span><button class="btn primary goAppointments">Go to appointments</button></div></div>`;document.body.appendChild(modal);modal.querySelector('.closeGate').onclick=()=>modal.remove();modal.querySelector('.goAppointments').onclick=()=>{modal.remove();state.page='appointments';render()}}
function requireConfirmedAppointment(service,action){let pilgrim=selectedPatient();if(!confirmedAppointmentFor(pilgrim,service)){showAppointmentRequired(pilgrim,service);return false}action();return true}
const ungatedScreening=openScreeningEncounter;openScreeningEncounter=function(){return requireConfirmedAppointment('screening',()=>ungatedScreening())};
const ungatedVaccination=openVaccinationEncounter;openVaccinationEncounter=function(){return requireConfirmedAppointment('vaccination',()=>ungatedVaccination())};
const ungatedNursingHistory=nursingHistoryEncounter;nursingHistoryEncounter=function(){return requireConfirmedAppointment('screening',()=>ungatedNursingHistory())};
function enforceRecordAppointmentTabs(){if(state.page!=='record'||!state.patient)return;[['screening','screening'],['vaccines','vaccination']].forEach(([tab,service])=>{let button=document.querySelector(`[data-tab="${tab}"]`);if(button&&!confirmedAppointmentFor(state.patient,service)){button.classList.add('appointment-locked');button.title='Confirmed appointment required';button.onclick=e=>{e.preventDefault();showAppointmentRequired(state.patient,service)}}})}
const gatedRender=render;render=function(){gatedRender();enforceRecordAppointmentTabs()};
