const professionalEmailDomain='hajjmed.gov.gh';
state.professionalEmails=state.professionalEmails||{
  admin:{address:'admin@hajjmed.gov.gh',status:'Active',owner:'Nana Osei'},
  medicaldirector:{address:'medical.director@hajjmed.gov.gh',status:'Active',owner:'Dr. Abdul Samed Tanko'},
  clinician:{address:'efua.mensah@hajjmed.gov.gh',status:'Active',owner:'Dr. Efua Mensah'},
  nurse:{address:'fatima.alhassan@hajjmed.gov.gh',status:'Active',owner:'Nurse Fatima Alhassan'},
  agent:{address:'al.barakah@hajjmed.gov.gh',status:'Active',owner:'Al-Barakah Travel'}
};
function emailSlug(value){return String(value||'user').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(dr|doctor|nurse|mr|mrs|ms|prof)\b/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'').slice(0,45)||'user'}
function proposedProfessionalEmail(name,role){let base=role==='medicaldirector'?'medical.director':role==='admin'?'administrator':emailSlug(name),candidate=`${base}@${professionalEmailDomain}`,used=new Set(Object.values(state.professionalEmails).map(x=>x.address).concat(state.pendingAccessRequests.map(x=>x.professionalEmail).filter(Boolean)));let n=2;while(used.has(candidate))candidate=`${base}.${n++}@${professionalEmailDomain}`;return candidate}
function installProfessionalEmailField(modal,type){let form=modal?.querySelector('form'),name=type==='agent'?$('#agentAgency'):$('#professionalName'),personal=type==='agent'?$('#agentEmail'):$('#clinicianEmail');if(!form||!name||!personal||$('#professionalEmailPreview'))return;let field=`<label class="field professional-email-field"><span>HajjMed professional email</span><input class="input" id="professionalEmailPreview" readonly value="Pending name / agency"><small>Reserved now and activated after identity, accreditation or licence approval. Personal email remains the recovery contact.</small></label>`;personal.closest('.field').insertAdjacentHTML('afterend',field);let update=()=>{$('#professionalEmailPreview').value=proposedProfessionalEmail(name.value,type==='agent'?'agent':($('#professionalRole')?.value||'clinician'))};name.addEventListener('input',update);name.addEventListener('change',update);$('#professionalRole')?.addEventListener('change',update);update();form.addEventListener('submit',()=>{let personalEmail=personal.value.trim().toLowerCase();setTimeout(()=>{let request=[...state.pendingAccessRequests].reverse().find(x=>x.email===personalEmail);if(request&&!request.professionalEmail){request.professionalEmail=$('#professionalEmailPreview')?.value||proposedProfessionalEmail(type==='agent'?request.agency:request.name,request.role);request.professionalEmailStatus='Reserved · activates after approval'}},0)})}
const professionalEmailAgentRegistration=showAgentRegistration;showAgentRegistration=function(){let result=professionalEmailAgentRegistration();installProfessionalEmailField($$('.modal').at(-1),'agent');return result};
const professionalEmailClinicianRegistration=showClinicianRegistration;showClinicianRegistration=function(){let result=professionalEmailClinicianRegistration();installProfessionalEmailField($$('.modal').at(-1),'clinician');return result};
const professionalEmailApproval=approveAccess;approveAccess=function(r){if(!r.professionalEmail)r.professionalEmail=proposedProfessionalEmail(r.type==='agent'?r.agency:r.name,r.role);r.professionalEmailStatus='Active';state.professionalEmails[r.id]={address:r.professionalEmail,status:'Active',owner:r.type==='agent'?r.agency:r.name};professionalEmailApproval(r);state.approvedPortalAccounts[r.professionalEmail]=r;otpContacts[r.role]={...(otpContacts[r.role]||{}),email:`${r.professionalEmail[0]}••••@${professionalEmailDomain}`};addPortalNotification(r.role==='agent'?`agent:${r.agency}`:r.role,'Professional email activated',`${r.professionalEmail} is active for HajjMed operational communication.`,'high');toast(`Professional email activated: ${r.professionalEmail}`)};
function professionalEmailManagementCard(){if(!['admin','medicaldirector'].includes(state.role)||state.page!=='backend'||$('#professionalEmailManagement'))return;let host=$('#content .page'),items=Object.values(state.professionalEmails);host?.insertAdjacentHTML('afterbegin',`<section class="section-card professional-email-card" id="professionalEmailManagement"><div class="section-heading"><b>@</b><div><h3>Professional email directory</h3><p>Managed operational identities for accredited agents, clinicians and leadership. Mailboxes activate only after account approval.</p></div></div><div class="professional-email-grid">${items.map(x=>`<div><small>${x.owner}</small><strong>${x.address}</strong><span class="email-status">${x.status}</span></div>`).join('')}</div><div class="form-actions"><span>Domain ownership, DNS records, mailbox licensing and retention policies must be configured with the approved email provider.</span><button class="btn outline" id="provisionProfessionalEmail">Provision approved account email</button></div></section>`);$('#provisionProfessionalEmail').onclick=()=>showAccessManagement()}
function installProfessionalEmailLoginIds(){let id=$('#loginId');if(!id)return;$$('.role').forEach(button=>button.addEventListener('click',()=>{let account=state.professionalEmails[button.dataset.role];if(account)id.value=account.address}))}
const professionalEmailLogin=login;login=function(){professionalEmailLogin();installProfessionalEmailLoginIds()};
const professionalEmailAccessManagement=showAccessManagement;showAccessManagement=function(){professionalEmailAccessManagement();$$('.access-request').forEach(card=>{let id=card.querySelector('[data-id]')?.dataset.id,request=state.pendingAccessRequests.find(x=>x.id===id);if(request&&!card.querySelector('.email-status'))card.querySelector('div')?.insertAdjacentHTML('beforeend',`<span class="email-status">Professional email: ${request.professionalEmail||proposedProfessionalEmail(request.type==='agent'?request.agency:request.name,request.role)} · ${request.status==='Approved'?'Active':'Reserved'}</span>`)})};
const professionalEmailRender=render;render=function(){professionalEmailRender();professionalEmailManagementCard()};
installProfessionalEmailLoginIds();
