import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import argon2 from 'argon2';
import { ghanaRegions } from '@hajjmed/contracts';
import { db } from '../lib/db.js';
import { requireRoles,assertPilgrimAccess } from '../lib/authz.js';
import { audit } from '../lib/audit.js';
import { queueRegistrationNotifications } from '../services/notifications.js';
import { createPilgrimWithUser, getPilgrimDetail, getPilgrimQrData, listPilgrimsForRole } from '../lib/pilgrim-data.js';

const createSchema=z.object({passportNumber:z.string().min(5).max(20),surname:z.string().min(1),givenNames:z.string().min(1),dateOfBirth:z.coerce.date(),sex:z.enum(['Female','Male','Other']),nationality:z.string().default('Ghanaian'),residenceRegion:z.enum(ghanaRegions),homeRegion:z.enum(ghanaRegions),email:z.union([z.string().trim().email(),z.literal('')]).optional(),phone:z.string().min(9),password:z.string().min(12),organizationId:z.string().uuid().optional(),photoObjectKey:z.string().optional()});

export async function pilgrimRoutes(app:FastifyInstance){
  app.post('/',async(req,reply)=>{const b=createSchema.parse(req.body);const passport=b.passportNumber.toUpperCase().replace(/[^A-Z0-9]/g,'');const phone=b.phone.replace(/\D/g,'');const email=b.email?.trim()||null;const created=await createPilgrimWithUser({email,phone,passwordHash:await argon2.hash(b.password),organizationId:b.organizationId,passport,surname:b.surname,givenNames:b.givenNames,dateOfBirth:b.dateOfBirth,sex:b.sex,nationality:b.nationality,residenceRegion:b.residenceRegion,homeRegion:b.homeRegion,photoObjectKey:b.photoObjectKey});await queueRegistrationNotifications({pilgrimName:`${b.givenNames} ${b.surname}`,passportNumber:passport,phone,email,recipientType:'PILGRIM'});await audit(req,{action:'CREATE',subjectType:'Pilgrim',subjectId:created.id,patientId:created.id,metadata:{residenceRegion:b.residenceRegion,homeRegion:b.homeRegion}});return reply.code(201).send({id:created.id,passportNumber:created.passportNumberNormalized})});
  app.get('/',{preHandler:requireRoles('AGENT','CLINICIAN','NURSE','ALLIED_HEALTH','ADMIN','MEDICAL_DIRECTOR')},async req=>listPilgrimsForRole({role:req.user.role,organizationId:req.user.organizationId}));
  app.get('/:id',{preHandler:requireRoles('PILGRIM','AGENT','CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async req=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const pilgrim=await getPilgrimDetail(id);await assertPilgrimAccess(req,pilgrim);await audit(req,{action:'READ',subjectType:'Pilgrim',subjectId:id,patientId:id});return pilgrim});
  app.get('/:id/qr-credential',{preHandler:requireRoles('PILGRIM','AGENT','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const pilgrim=await getPilgrimQrData(id);await assertPilgrimAccess(req,pilgrim);const screening=Array.isArray(pilgrim.screenings)?pilgrim.screenings[0]:undefined;if(!screening||screening.outcome!=='GREEN'||!screening.authenticatedAt||!screening.administratorAuthenticatedAt)return reply.code(403).send({error:{code:'QR_CREDENTIAL_NOT_RELEASED',message:'The unified QR credential and certificates require GREEN clearance plus authentication by both the Medical Director and Administrator'}});const token=app.jwt.sign({sub:`credential:${id}`,role:req.user.role,sessionId:req.user.sessionId,pilgrimId:id,credential:true} as any,{expiresIn:'10m'});await audit(req,{action:'EXPORT',subjectType:'UnifiedHajjQrCredential',subjectId:id,patientId:id,metadata:{accessedByRole:req.user.role}});return {pilgrim:{id:pilgrim.id,name:`${pilgrim.givenNames} ${pilgrim.surname}`,passportNumber:pilgrim.passportNumberNormalized,photoObjectKey:pilgrim.photoObjectKey},summary:{allergies:pilgrim.allergies,medications:pilgrim.medications,immunizations:pilgrim.immunizations,fitnessCertificateReleased:true},credentialToken:token,expiresInSeconds:600}});
}
