import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { canOverride,requireRoles } from '../lib/authz.js';
import { audit } from '../lib/audit.js';
import { allocateProfessionalEmail } from '../services/professional-email.js';
import { queueDueAdmissionUpdateReminders,queueDueAppointmentReminders } from '../services/notifications.js';

export async function adminRoutes(app:FastifyInstance){
  app.get('/dashboard',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async()=>{const [pilgrims,appointments,screenings,openEmergencies]=await Promise.all([prisma.pilgrim.count(),prisma.appointment.count(),prisma.screening.count(),prisma.encounter.count({where:{type:'EMERGENCY',status:{in:['PLANNED','IN_PROGRESS']}}})]);return {pilgrims,appointments,screenings,openEmergencies}});
  app.get('/reports/dispositions',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async req=>{const q=z.object({from:z.coerce.date().optional(),to:z.coerce.date().optional(),facilityId:z.string().uuid().optional()}).parse(req.query),where={startedAt:{gte:q.from,lte:q.to},facilityId:q.facilityId,disposition:{not:null}};const [totals,referrals]=await Promise.all([prisma.encounter.groupBy({by:['disposition'],where,_count:{_all:true}}),prisma.encounter.findMany({where:{...where,referralPlace:{not:null}},select:{disposition:true,referralPlace:true,facilityId:true,startedAt:true},orderBy:{startedAt:'desc'},take:1000})]);return {dimensions:['disposition','referralPlace','facilityId','startedAt'],totals,referrals}});
  app.patch('/facilities/:id/location',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),{location}=z.object({location:z.string().trim().min(2).max(300)}).parse(req.body),facility=await prisma.facility.update({where:{id},data:{location}});await audit(req,{action:'UPDATE',subjectType:'FacilityLocation',subjectId:id,reason:'Authorised clinic location update',metadata:{location}});return reply.send(facility)});
  app.post('/jobs/appointment-reminders',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async req=>{const result=await queueDueAppointmentReminders();await audit(req,{action:'CREATE',subjectType:'AppointmentReminderJob',metadata:result});return result});
  app.post('/jobs/admission-update-reminders',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async req=>{const result=await queueDueAdmissionUpdateReminders();await audit(req,{action:'CREATE',subjectType:'AdmissionUpdateReminderJob',metadata:result});return result});
  app.patch('/users/:id/status',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const {status,reason}=z.object({status:z.enum(['ACTIVE','SUSPENDED','DISABLED']),reason:z.string().min(5)}).parse(req.body);const target=await prisma.user.findUniqueOrThrow({where:{id}});if(!canOverride(req.user.role,target.role))return reply.code(403).send({error:{code:'OVERRIDE_FORBIDDEN',message:'This account outranks or equals the acting user'}});const eligibleForProfessionalEmail=['AGENT','CLINICIAN','NURSE','ALLIED_HEALTH','PHARMACIST','ADMIN','MEDICAL_DIRECTOR'].includes(target.role),professionalEmail=status==='ACTIVE'&&eligibleForProfessionalEmail&&!target.professionalEmail?await allocateProfessionalEmail({displayName:target.displayName,role:target.role}):undefined;const changed=await prisma.user.update({where:{id},data:{status,professionalEmail},select:{id:true,displayName:true,role:true,status:true,email:true,professionalEmail:true}});await audit(req,{action:'OVERRIDE',subjectType:'User',subjectId:id,reason,metadata:{status,professionalEmailCreated:Boolean(professionalEmail)}});return changed});
  app.post('/screenings/:id/authenticate-certificate',{preHandler:requireRoles('MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),{attestation}=z.object({attestation:z.literal(true)}).parse(req.body),screening=await prisma.screening.findUniqueOrThrow({where:{id},include:{pilgrim:{include:{immunizations:true}}}});if(screening.outcome!=='GREEN')return reply.code(409).send({error:{code:'SCREENING_NOT_CLEARED',message:'Medical Director authentication requires a completed GREEN screening outcome'}});if(!screening.pilgrim.immunizations.length)return reply.code(409).send({error:{code:'VACCINATION_INCOMPLETE',message:'Medical Director authentication requires completed vaccination records'}});if(screening.authenticatedAt)return {id:screening.id,authenticatedAt:screening.authenticatedAt,authenticatedByUserId:screening.authenticatedByUserId};const authenticated=await prisma.screening.update({where:{id},data:{reviewedByUserId:req.user.sub,authenticatedByUserId:req.user.sub,authenticatedAt:new Date()}});await audit(req,{action:'UPDATE',subjectType:'MedicalFitnessCertificate',subjectId:id,patientId:screening.pilgrimId,reason:'Medical Director reviewed and authenticated completed screening and vaccination records',metadata:{attestation}});return authenticated});
}
