import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { requireRoles,assertPilgrimAccess } from '../lib/authz.js';
import { audit } from '../lib/audit.js';
import type { AppointmentPurpose,Prisma } from '@prisma/client';
import { queueCertificateReadyNotifications,queuePilgrimPortalUpdateNotifications,queueScreeningOutcomeNotifications } from '../services/notifications.js';
import {mayReviewRegulatoryHardRed,regulatoryExclusionCodes,regulatorySourceVersion,requiresRegulatoryHardRed} from '../services/regulatory-screening-policy.js';
import { publishClinicalChange,subscribeClinicalChanges } from '../services/clinical-events.js';

const screening=z.object({pilgrimId:z.string().uuid(),questionnaireVersion:z.string(),outcome:z.enum(['GREEN','AMBER','RED']),positiveFindings:z.array(z.object({code:z.string(),display:z.string(),severity:z.string().optional()})),rationale:z.string().min(3),recommendations:z.string().optional(),ruleSetVersion:z.string(),regulatoryExclusionCodes:z.array(z.enum(regulatoryExclusionCodes)).default([]),regulatoryExclusionEvidence:z.array(z.object({code:z.enum(regulatoryExclusionCodes),historyRemark:z.string().trim().min(5).max(2000)})).default([])}).superRefine((value,ctx)=>{for(const code of value.regulatoryExclusionCodes)if(!value.regulatoryExclusionEvidence.some(e=>e.code===code))ctx.addIssue({code:'custom',path:['regulatoryExclusionEvidence'],message:`Medical-history remarks are required for regulatory exclusion ${code}`})});
const encounter=z.object({pilgrimId:z.string().uuid(),facilityId:z.string().uuid(),type:z.enum(['CLINIC','ACUTE_CARE','EMERGENCY']),chiefComplaint:z.string().optional(),diagnosisCodes:z.array(z.object({system:z.string(),code:z.string(),display:z.string()})).default([]),manualDiagnosis:z.string().trim().min(2).max(300).optional(),summary:z.string().min(3),interventions:z.array(z.unknown()),disposition:z.enum(['DISCHARGED_STABLE','OBSERVATION','ADMITTED','TRANSFERRED_EVACUATED','REFERRED','DECEASED']).optional(),referralPlace:z.string().trim().max(200).optional(),admissionHospital:z.string().trim().max(200).optional(),admissionWard:z.string().trim().max(120).optional(),treatmentFor:z.string().trim().max(1000).optional(),dailyUpdate:z.string().trim().max(2000).optional(),deathSummary:z.string().trim().max(2000).optional(),status:z.enum(['PLANNED','IN_PROGRESS','FINISHED','CANCELLED']).default('FINISHED')}).superRefine((v,ctx)=>{if(!v.diagnosisCodes.length&&!v.manualDiagnosis)ctx.addIssue({code:'custom',path:['manualDiagnosis'],message:'Select an ICD diagnosis or enter a manual diagnosis'});if(['TRANSFERRED_EVACUATED','REFERRED'].includes(v.disposition??'')&&!v.referralPlace)ctx.addIssue({code:'custom',path:['referralPlace'],message:'Place of referral is required for referral or transfer'});if(v.disposition==='ADMITTED')for(const key of ['admissionHospital','admissionWard','treatmentFor','dailyUpdate'] as const)if(!v[key])ctx.addIssue({code:'custom',path:[key],message:'Required for an admitted pilgrim'});if(v.disposition==='DECEASED'&&!v.deathSummary)ctx.addIssue({code:'custom',path:['deathSummary'],message:'A death summary is required'})});
const immunization=z.object({pilgrimId:z.string().uuid(),facilityId:z.string().uuid(),vaccineCode:z.string().min(1),vaccineDisplay:z.string().min(1),lotNumber:z.string().trim().min(1),expiryDate:z.coerce.date(),administeredAt:z.coerce.date()});
const dispositionDetails=z.object({placeOfDeath:z.string().trim().max(200).optional(),timeOfDeath:z.coerce.date().optional()});
const carePlan=z.object({selections:z.array(z.string().trim().min(1)).min(1),responsibleTeam:z.string().trim().min(2),reviewDate:z.coerce.date().nullable().optional(),clinicalRationale:z.string().trim().min(3),sharedSummary:z.string().trim().min(3),status:z.enum(['ACTIVE','COMPLETED','CANCELLED']).default('ACTIVE')});
const clearanceOverride=z.object({reason:z.string().trim().min(20).max(4000),accountabilityAccepted:z.literal(true)});
const leadership=(req:FastifyRequest)=>mayReviewRegulatoryHardRed(req.user.role);

async function requireClinicalAppointment(req:FastifyRequest,pilgrimId:string,purposes:AppointmentPurpose[]){
  if(leadership(req))return;
  const appointment=await prisma.appointment.findFirst({where:{pilgrimId,purpose:{in:purposes},status:{in:['CONFIRMED','CHECKED_IN']}},orderBy:{startsAt:'desc'},select:{id:true,reference:true}});
  if(appointment)return appointment;
  await audit(req,{action:'BREAK_GLASS',subjectType:'ClinicalAccessDenied',patientId:pilgrimId,reason:`No confirmed ${purposes.join('/')} appointment`});
  throw Object.assign(new Error('A matching confirmed appointment is required'),{statusCode:403,code:'CONFIRMED_APPOINTMENT_REQUIRED'});
}

async function requireActiveFacility(facilityId:string){
  const facility=await prisma.facility.findUniqueOrThrow({where:{id:facilityId},select:{id:true,active:true}});
  if(!facility.active)throw Object.assign(new Error('Clinical entries cannot be recorded at an inactive facility'),{statusCode:409,code:'FACILITY_INACTIVE'});
}

export async function clinicalRoutes(app:FastifyInstance){
  app.addHook('onResponse',async(req,reply)=>{if(['POST','PUT','PATCH'].includes(req.method)&&reply.statusCode<400)publishClinicalChange({type:'CLINICAL_DOCUMENTATION_UPDATED',actorUserId:req.user.sub,actorRole:req.user.role,occurredAt:new Date().toISOString(),requestId:req.id})});
  app.get('/events',{preHandler:requireRoles('CLINICIAN','NURSE','ALLIED_HEALTH','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{reply.hijack();reply.raw.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});reply.raw.write(`event: ready\ndata: ${JSON.stringify({connectedAt:new Date().toISOString()})}\n\n`);const unsubscribe=subscribeClinicalChanges(event=>reply.raw.write(`event: clinical-change\ndata: ${JSON.stringify(event)}\n\n`)),heartbeat=setInterval(()=>reply.raw.write(': keep-alive\n\n'),25000);req.raw.on('close',()=>{clearInterval(heartbeat);unsubscribe()})});
  app.post('/screenings',{preHandler:requireRoles('CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const b=screening.parse(req.body),hardRed=requiresRegulatoryHardRed(b.regulatoryExclusionCodes),pilgrim=await prisma.pilgrim.findUniqueOrThrow({where:{id:b.pilgrimId},include:{user:true,organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'},take:1}}}}});await requireClinicalAppointment(req,b.pilgrimId,['SCREENING','SCREENING_AND_VACCINATION']);
    if(hardRed&&b.outcome!=='RED')return reply.code(422).send({error:{code:'REGULATORY_RED_REQUIRED',message:'A Saudi MOH minimum-physical-ability exclusion criterion requires a protected RED outcome'}});
    const existing=await prisma.screening.findFirst({where:{pilgrimId:b.pilgrimId,supersedesId:null},select:{id:true,outcome:true,performedAt:true}});if(existing)return reply.code(409).send({error:{code:'SCREENING_ALREADY_EXISTS',message:'This pilgrim already has a Hajj 2027 screening record. Use the authorised review endpoint.',existing}});
    const {regulatoryExclusionCodes:exclusions,...screeningData}=b;const row=await prisma.screening.create({data:{...screeningData,positiveFindings:b.positiveFindings as Prisma.InputJsonValue,regulatoryHardRed:hardRed,regulatoryExclusionCodes:exclusions as Prisma.InputJsonValue,regulatorySourceVersion:hardRed?regulatorySourceVersion:null,regulatoryLockedAt:hardRed?new Date():null,performedByUserId:req.user.sub}}),notice={pilgrimName:`${pilgrim.givenNames} ${pilgrim.surname}`,outcome:b.outcome,recommendations:b.recommendations},agent=pilgrim.organization?.users[0];await Promise.all([queueScreeningOutcomeNotifications({...notice,phone:pilgrim.user?.phoneNormalized,email:pilgrim.user?.email,recipientType:'PILGRIM'}),queueScreeningOutcomeNotifications({...notice,phone:agent?.phoneNormalized,email:agent?.email,recipientType:'AGENT'})]);await audit(req,{action:'CREATE',subjectType:hardRed?'RegulatoryHardRedScreening':'Screening',subjectId:row.id,patientId:b.pilgrimId,metadata:{regulatoryHardRed:hardRed,regulatoryExclusionCodes:exclusions,regulatorySourceVersion:hardRed?regulatorySourceVersion:null}});return reply.code(201).send(row)
  });
  app.post('/screenings/:id/reviews',{preHandler:requireRoles('CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {id}=z.object({id:z.string().uuid()}).parse(req.params),b=screening.parse(req.body),original=await prisma.screening.findUniqueOrThrow({where:{id}});if(original.pilgrimId!==b.pilgrimId)return reply.code(422).send({error:{code:'PILGRIM_MISMATCH',message:'The review must belong to the original pilgrim'}});if(original.regulatoryHardRed&&!leadership(req)){await audit(req,{action:'BREAK_GLASS',subjectType:'RegulatoryHardRedReviewDenied',subjectId:id,patientId:original.pilgrimId,reason:'Protected Saudi MOH RED outcome may be reviewed only by Administrator or Medical Director'});return reply.code(423).send({error:{code:'REGULATORY_RED_LOCKED',message:'This protected RED outcome may be reviewed or amended only by the Administrator or Medical Director'}})}if(original.outcome==='GREEN'&&!leadership(req))return reply.code(409).send({error:{code:'REVIEW_NOT_REQUIRED',message:'A cleared screening cannot enter the routine review workflow'}});await requireClinicalAppointment(req,b.pilgrimId,['REVIEW']);const priorReview=await prisma.screening.findFirst({where:{supersedesId:id},select:{id:true}});if(priorReview&&!leadership(req))return reply.code(409).send({error:{code:'REVIEW_ALREADY_RECORDED',message:'This booked review has already been recorded'}});const pilgrim=await prisma.pilgrim.findUniqueOrThrow({where:{id:b.pilgrimId},include:{user:true,organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'},take:1}}}}}),{regulatoryExclusionCodes:reviewExclusions,...reviewData}=b,row=await prisma.screening.create({data:{...reviewData,positiveFindings:b.positiveFindings as Prisma.InputJsonValue,regulatoryHardRed:reviewExclusions.length>0,regulatoryExclusionCodes:reviewExclusions as Prisma.InputJsonValue,regulatorySourceVersion:reviewExclusions.length?regulatorySourceVersion:null,regulatoryLockedAt:reviewExclusions.length?new Date():null,performedByUserId:req.user.sub,supersedesId:id}}),notice={pilgrimName:`${pilgrim.givenNames} ${pilgrim.surname}`,outcome:b.outcome,recommendations:b.recommendations},agent=pilgrim.organization?.users[0];await Promise.all([queueScreeningOutcomeNotifications({...notice,phone:pilgrim.user?.phoneNormalized,email:pilgrim.user?.email,recipientType:'PILGRIM'}),queueScreeningOutcomeNotifications({...notice,phone:agent?.phoneNormalized,email:agent?.email,recipientType:'AGENT'})]);await queuePilgrimPortalUpdateNotifications({pilgrimId:b.pilgrimId,updateType:'Medical screening review'});await audit(req,{action:'CREATE',subjectType:original.regulatoryHardRed?'RegulatoryHardRedLeadershipReview':'ScreeningReview',subjectId:row.id,patientId:b.pilgrimId,metadata:{supersedesId:id,originalRegulatoryHardRed:original.regulatoryHardRed,role:req.user.role}});return reply.code(201).send(row)
  });
  app.post('/screenings/:id/clearance-override',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {id}=z.object({id:z.string().uuid()}).parse(req.params),body=clearanceOverride.parse(req.body),original=await prisma.screening.findUniqueOrThrow({where:{id},include:{pilgrim:{include:{user:true,organization:{include:{users:{where:{role:'AGENT',status:'ACTIVE'},take:1}}}}}}});
    if(original.outcome!=='AMBER')return reply.code(409).send({error:{code:'AMBER_OVERRIDE_ONLY',message:'Only an AMBER clinical-review outcome may be overridden to GREEN through this endpoint'}});
    const existing=await prisma.screening.findFirst({where:{supersedesId:id,outcome:'GREEN'},select:{id:true}});if(existing)return reply.code(409).send({error:{code:'CLEARANCE_OVERRIDE_ALREADY_EXISTS',message:'This AMBER screening already has a GREEN clearance override',existingId:existing.id}});
    const row=await prisma.screening.create({data:{pilgrimId:original.pilgrimId,questionnaireVersion:original.questionnaireVersion,outcome:'GREEN',positiveFindings:original.positiveFindings as Prisma.InputJsonValue,rationale:body.reason,recommendations:original.recommendations,ruleSetVersion:original.ruleSetVersion,performedByUserId:req.user.sub,supersedesId:id}}),pilgrim=original.pilgrim,notice={pilgrimName:`${pilgrim.givenNames} ${pilgrim.surname}`,outcome:'GREEN' as const,recommendations:'Leadership reviewed the AMBER outcome and authorised GREEN medical clearance.'},agent=pilgrim.organization?.users[0];
    await Promise.all([queueScreeningOutcomeNotifications({...notice,phone:pilgrim.user?.phoneNormalized,email:pilgrim.user?.email,recipientType:'PILGRIM'}),queueScreeningOutcomeNotifications({...notice,phone:agent?.phoneNormalized,email:agent?.email,recipientType:'AGENT'})]);await audit(req,{action:'UPDATE',subjectType:'ScreeningClearanceOverride',subjectId:row.id,patientId:original.pilgrimId,reason:body.reason,metadata:{originalScreeningId:id,from:'AMBER',to:'GREEN',role:req.user.role,accountabilityAccepted:true}});return reply.code(201).send(row)
  });
  app.post('/screenings/:id/fitness-authentication',{preHandler:requireRoles('ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {id}=z.object({id:z.string().uuid()}).parse(req.params),screen=await prisma.screening.findUniqueOrThrow({where:{id},include:{pilgrim:{select:{id:true}}}});
    if(screen.outcome!=='GREEN')return reply.code(409).send({error:{code:'FITNESS_REQUIREMENTS_INCOMPLETE',message:'Only a GREEN screening outcome can enter fitness-certificate authentication'}});
    const vaccinationCount=await prisma.immunization.count({where:{pilgrimId:screen.pilgrimId}});if(!vaccinationCount)return reply.code(409).send({error:{code:'VACCINATION_REQUIREMENTS_INCOMPLETE',message:'A verified mandatory vaccination record is required before authentication'}});
    const field=req.user.role==='ADMIN'?{administratorAuthenticatedByUserId:req.user.sub,administratorAuthenticatedAt:new Date()}:{authenticatedByUserId:req.user.sub,authenticatedAt:new Date()};
    const already=req.user.role==='ADMIN'?screen.administratorAuthenticatedAt:screen.authenticatedAt;if(already)return reply.code(409).send({error:{code:'ROLE_AUTHENTICATION_ALREADY_RECORDED',message:'This role has already authenticated the certificate'}});
    const updated=await prisma.screening.update({where:{id},data:field,select:{id:true,pilgrimId:true,authenticatedByUserId:true,authenticatedAt:true,administratorAuthenticatedByUserId:true,administratorAuthenticatedAt:true}});const fullyAuthenticated=Boolean(updated.authenticatedAt&&updated.administratorAuthenticatedAt);if(fullyAuthenticated)await queueCertificateReadyNotifications({pilgrimId:screen.pilgrimId,certificateType:'Hajj medical fitness certificate',certificateReference:`HMFC-2027-${screen.pilgrimId.slice(0,8).toUpperCase()}`});else await queuePilgrimPortalUpdateNotifications({pilgrimId:screen.pilgrimId,updateType:'Fitness certificate authentication status'});await audit(req,{action:'UPDATE',subjectType:'FitnessCertificateAuthentication',subjectId:id,patientId:screen.pilgrimId,metadata:{role:req.user.role,fullyAuthenticated}});return updated
  });
  app.get('/screenings/:id/fitness-certificate',{preHandler:requireRoles('PILGRIM','AGENT','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {id}=z.object({id:z.string().uuid()}).parse(req.params),screen=await prisma.screening.findUniqueOrThrow({where:{id},include:{pilgrim:true}});await assertPilgrimAccess(req,screen.pilgrim);
    if(screen.outcome!=='GREEN'||!screen.authenticatedAt||!screen.administratorAuthenticatedAt)return reply.code(403).send({error:{code:'CERTIFICATE_NOT_RELEASED',message:'Certificate requires GREEN clearance and authentication by both the Medical Director and Administrator'}});
    await audit(req,{action:'EXPORT',subjectType:'FitnessCertificate',subjectId:id,patientId:screen.pilgrimId});return {certificateNumber:`HMFC-2027-${screen.pilgrim.passportNumberNormalized}`,screeningId:id,pilgrim:{id:screen.pilgrim.id,name:`${screen.pilgrim.givenNames} ${screen.pilgrim.surname}`,passportNumber:screen.pilgrim.passportNumberNormalized},medicalDirectorAuthenticatedAt:screen.authenticatedAt,administratorAuthenticatedAt:screen.administratorAuthenticatedAt}
  });
  app.post('/immunizations',{preHandler:requireRoles('CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const b=immunization.parse(req.body),lot=b.lotNumber.toUpperCase();await requireClinicalAppointment(req,b.pilgrimId,['VACCINATION','SCREENING_AND_VACCINATION']);await requireActiveFacility(b.facilityId);if(b.expiryDate<b.administeredAt)return reply.code(422).send({error:{code:'VACCINE_EXPIRED_AT_ADMINISTRATION',message:'Vaccine expiry must be after the administration date'}});const existing=await prisma.immunization.findFirst({where:{pilgrimId:b.pilgrimId,vaccineCode:b.vaccineCode,lotNumber:lot,administeredAt:b.administeredAt},select:{id:true}});if(existing)return reply.code(409).send({error:{code:'IMMUNIZATION_DUPLICATE',message:'This vaccine administration is already recorded for the pilgrim.',existingId:existing.id}});const row=await prisma.immunization.create({data:{...b,lotNumber:lot,performerUserId:req.user.sub}});await queuePilgrimPortalUpdateNotifications({pilgrimId:b.pilgrimId,updateType:'Vaccination record'});await audit(req,{action:'CREATE',subjectType:'Immunization',subjectId:row.id,patientId:b.pilgrimId});return reply.code(201).send(row)
  });
  app.post('/encounters',{preHandler:requireRoles('CLINICIAN','NURSE','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const core=encounter.parse(req.body),extra=dispositionDetails.parse(req.body),b={...core,...extra};
    const referred=['REFERRED','TRANSFERRED_EVACUATED'].includes(b.disposition??'');
    if(referred&&(!b.admissionHospital||!b.admissionWard||!b.treatmentFor||!b.dailyUpdate))return reply.code(422).send({error:{code:'REFERRAL_DETAILS_REQUIRED',message:'Referral or transfer requires destination, ward, condition being treated and daily summary'}});
    if(b.disposition==='DECEASED'&&(!b.placeOfDeath||!b.timeOfDeath||!b.deathSummary))return reply.code(422).send({error:{code:'DEATH_DETAILS_REQUIRED',message:'Deceased disposition requires place, time and clinical summary'}});
    await requireActiveFacility(b.facilityId);
    const row=await prisma.encounter.create({data:{...b,diagnosisCodes:b.diagnosisCodes as Prisma.InputJsonValue,interventions:b.interventions as Prisma.InputJsonValue,clinicianUserId:req.user.sub,dailyUpdateDueAt:referred?new Date(Date.now()+86400000):undefined,endedAt:b.status==='FINISHED'?new Date():undefined}});
    await queuePilgrimPortalUpdateNotifications({pilgrimId:b.pilgrimId,updateType:`Clinical disposition: ${b.disposition??'recorded'}`});
    await audit(req,{action:'CREATE',subjectType:'Encounter',subjectId:row.id,patientId:b.pilgrimId,metadata:{disposition:b.disposition,admissionHospital:b.admissionHospital,admissionWard:b.admissionWard,referralPlace:b.referralPlace}});
    return reply.code(201).send(row)
  });
  app.patch('/encounters/:id/daily-update',{preHandler:requireRoles('CLINICIAN','NURSE','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),{update}=z.object({update:z.string().trim().min(3).max(2000)}).parse(req.body),current=await prisma.encounter.findUniqueOrThrow({where:{id}});if(!['REFERRED','TRANSFERRED_EVACUATED'].includes(current.disposition??''))return reply.code(409).send({error:{code:'NOT_REFERRED_OR_TRANSFERRED',message:'Daily updates apply only to referred or transferred pilgrims'}});const row=await prisma.encounter.update({where:{id},data:{dailyUpdate:update,dailyUpdateDueAt:new Date(Date.now()+86400000)}});await audit(req,{action:'UPDATE',subjectType:'ReferralDailyUpdate',subjectId:id,patientId:current.pilgrimId});return row});
  app.post('/encounters/:id/documents',{preHandler:requireRoles('CLINICIAN','NURSE','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),b=z.object({category:z.enum(['ADMISSION_SUMMARY','DISCHARGE_SUMMARY','DEATH_CERTIFICATE','BURIAL_PERMIT']),objectKey:z.string().min(3),mimeType:z.string().min(3),sha256:z.string().regex(/^[a-f0-9]{64}$/i),interpretation:z.string().max(1000).optional()}).parse(req.body),encounterRow=await prisma.encounter.findUniqueOrThrow({where:{id}});const document=await prisma.clinicalDocument.create({data:{pilgrimId:encounterRow.pilgrimId,encounterId:id,category:b.category,objectKey:b.objectKey,mimeType:b.mimeType,sha256:b.sha256,interpretation:b.interpretation,uploadedByUserId:req.user.sub}});await audit(req,{action:'CREATE',subjectType:'ClinicalDocument',subjectId:document.id,patientId:encounterRow.pilgrimId,metadata:{encounterId:id,category:b.category}});return reply.code(201).send(document)});
  app.patch('/encounters/:id/death-details',{preHandler:requireRoles('CLINICIAN','NURSE','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params),details=dispositionDetails.required().parse(req.body),current=await prisma.encounter.findUniqueOrThrow({where:{id}});if(current.disposition!=='DECEASED')return reply.code(409).send({error:{code:'NOT_DECEASED',message:'Death details apply only to a deceased disposition'}});const row=await prisma.encounter.update({where:{id},data:details});await audit(req,{action:'UPDATE',subjectType:'EncounterDeathDetails',subjectId:id,patientId:current.pilgrimId});return row});
  app.get('/care-plans/:pilgrimId',{preHandler:requireRoles('PILGRIM','AGENT','CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {pilgrimId}=z.object({pilgrimId:z.string().uuid()}).parse(req.params),pilgrim=await prisma.pilgrim.findUniqueOrThrow({where:{id:pilgrimId},select:{id:true,organizationId:true}});await assertPilgrimAccess(req,pilgrim);const plan=await prisma.carePlan.findUnique({where:{pilgrimId}});if(!plan)return reply.code(404).send({error:{code:'CARE_PLAN_NOT_FOUND',message:'No approved care plan is available'}});await audit(req,{action:'READ',subjectType:'CarePlan',subjectId:plan.id,patientId:pilgrimId});if(req.user.role==='PILGRIM'||req.user.role==='AGENT')return {id:plan.id,pilgrimId:plan.pilgrimId,selections:plan.selections,responsibleTeam:plan.responsibleTeam,reviewDate:plan.reviewDate,sharedSummary:plan.sharedSummary,status:plan.status,updatedAt:plan.updatedAt};return plan
  });
  app.put('/care-plans/:pilgrimId',{preHandler:requireRoles('CLINICIAN','ADMIN','MEDICAL_DIRECTOR')},async(req,reply)=>{
    const {pilgrimId}=z.object({pilgrimId:z.string().uuid()}).parse(req.params),body=carePlan.parse(req.body);await prisma.pilgrim.findUniqueOrThrow({where:{id:pilgrimId},select:{id:true}});const existing=await prisma.carePlan.findUnique({where:{pilgrimId},select:{id:true,updatedAt:true}});if(existing&&!leadership(req)&&Date.now()-existing.updatedAt.getTime()>=86400000)return reply.code(423).send({error:{code:'CARE_PLAN_LOCKED',message:'Care-plan entries become read only after 24 hours; leadership review is required'}});const data={...body,selections:body.selections as Prisma.InputJsonValue,updatedByUserId:req.user.sub};const plan=existing?await prisma.carePlan.update({where:{pilgrimId},data}):await prisma.carePlan.create({data:{...data,pilgrimId,createdByUserId:req.user.sub}});await queuePilgrimPortalUpdateNotifications({pilgrimId,updateType:'Care plan'});await audit(req,{action:existing?'UPDATE':'CREATE',subjectType:'CarePlan',subjectId:plan.id,patientId:pilgrimId});return reply.code(existing?200:201).send(plan)
  });
}
